app/models.py
from datetime import datetime, timezone, timedelta
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login
import base64
import os


class User(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True, unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))
    forecast_requests: so.WriteOnlyMapped["Forecast_request"] = so.relationship(
        back_populates="from_user"
    )
    token = db.Column(db.String(32), index=True, unique=True)
    token_expiration = db.Column(db.DateTime)

    def __repr__(self):
        return "<User {}>".format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_token(self, expires_in=3600):
        now = datetime.now(timezone.utc)
        if self.token and self.token_expiration.replace(
            tzinfo=timezone.utc
        ) > now + timedelta(seconds=60):
            return self.token
        self.token = base64.b64encode(os.urandom(24)).decode('utf-8')
        self.token_expiration = now + timedelta(seconds=expires_in)
        db.session.add(self)
        return self.token

    def revoke_token(self):
        self.token_expiration = datetime.now(timezone.utc) - timedelta(seconds=1)

    @staticmethod
    def check_token(token):
        user = db.session.scalar(sa.select(User).where(User.token == token))
        if user is None or user.token_expiration.replace(
            tzinfo=timezone.utc
        ) < datetime.now(timezone.utc):
            return None
        return user


class City(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), index=True, unique=True)
    forecast_requests: so.WriteOnlyMapped["Forecast_request"] = so.relationship(
        back_populates="city"
    )

    def __repr__(self):
        return f"<City {self.name}>"

    def to_dict(self):
        data = {
            "id": self.id,
            "name": self.name,
            "number_of_requests": number_of_requests(self.id),
        }
        return data


class Forecast_request(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    timestamp: so.Mapped[datetime] = so.mapped_column(
        index=True, default=lambda: datetime.now(timezone.utc)
    )
    user_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(User.id), index=True)
    from_user: so.Mapped[User] = so.relationship(back_populates="forecast_requests")
    city_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(City.id), index=True)
    city: so.Mapped[City] = so.relationship(back_populates="forecast_requests")

    def __repr__(self):
        return f"<Forecast_request from {self.from_user} at {self.city}. Created at {self.timestamp}"


@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))

def number_of_requests(c):
    query = Forecast_request.query.filter(Forecast_request.city_id==c).count()
    return query

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("Remember Me")
    submit = SubmitField("Sign In")


class CityForm(FlaskForm):
    name = StringField("Название города", validators=[DataRequired()])
    submit = SubmitField("OK")

app/__init__.py
from flask import Flask, current_app
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    
    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix='/api')
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)



    return app

from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import requests, errors, tokens

app/api/auth.py
import sqlalchemy as sa
from flask_httpauth import HTTPBasicAuth, HTTPTokenAuth
from app import db
from app.models import User
from app.api.errors import error_response

basic_auth = HTTPBasicAuth()
token_auth = HTTPTokenAuth()


@basic_auth.verify_password
def verify_password(username, password):
    user = db.session.scalar(sa.select(User).where(User.username == username))
    if user and user.check_password(password):
        return user


@basic_auth.error_handler
def basic_auth_error(status):
    return error_response(status)


@token_auth.verify_token
def verify_token(token):
    return User.check_token(token) if token else None


@token_auth.error_handler
def token_auth_error(status):
    return error_response(status)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user
import sqlalchemy as sa
from app import db
from app.main.forms import LoginForm, CityForm
from app.models import User, City, Forecast_request
from app.utils.weather import get_coordinates, get_weather
from app.main import bp


@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
def index():
    form = LoginForm()
    city_form = CityForm()
    city = None
    temp_data = None
    daily_weather = None
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == form.username.data)
        )
        if user is None:
            new_user = User(username=form.username.data)
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.commit()
            flash(f"Добро пожаловать, {new_user.username}!")
            login_user(new_user, remember=form.remember_me.data)
        elif not user.check_password(form.password.data):
            flash("Пароль неверный!")
        else:
            login_user(user, remember=form.remember_me.data)
    if city_form.validate_on_submit():
        flash("Город {}".format(city_form.name.data))
        city = city_form.name.data
        coordinates = get_coordinates(city)
        if coordinates is None:
            flash("Город не найден")
        else:
            dbcity = db.session.scalar(
                sa.select(City).where(City.name == city.lower())
            )
            if dbcity is None:
                dbcity = City(name=city.lower())
                db.session.add(dbcity)
                db.session.commit()
            if current_user.is_authenticated:
                forecast = Forecast_request(from_user=current_user, city=dbcity)
                db.session.add(forecast)
                db.session.commit()
            hourly_weather, daily_weather = get_weather(coordinates=coordinates)
            temp_data = hourly_weather[["date", "temperature_2m"]].to_dict(orient="records")
    return render_template(
        "index.html",
        title="Введите город",
        form=form,
        city_form=city_form,
        city=city,
        authenticated=current_user.is_authenticated,
        user=current_user,
        temp_data=temp_data,
        weather_data=daily_weather
    )


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='main.css') }}"
    />
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  </head>
  <body>
    <hr />
    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
  </body>
</html>

app/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="nav">
  Прогноз погоды:
  <a href="{{ url_for('main.index') }}">Home</a>
  {% if current_user.is_anonymous %}
  <button id="loginButton">Вход</button>
  {% else %}
  <a href="{{ url_for('main.logout') }}">Выход</a>
  {% endif %}
</div>

<div class="login-form" id="loginForm">
  <form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <h2>Вход</h2>
    <p>
      {{ form.username.label }}<br />
      {{ form.username(size=32) }}<br />
      {% for error in form.username.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p class="input">
      {{ form.password.label }}<br />
      {{ form.password(size=32) }}<br />
      {% for error in form.password.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <button>{{ form.submit() }}</button>
  </form>
</div>
<div class="container">
  <form action="" method="post" novalidate>
    {{ city_form.hidden_tag() }}
    <h1>Введите город</h1>
    <p id="cityInput">
      {{ city_form.name.label }}<br />
      {{ city_form.name(size=32) }}<br />
      {% for error in city_form.name.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>

    <p id="okButton">{{ city_form.submit() }}</p>
  </form>
</div>
{% if city %}
<div class="weather">
  <h1>Погода в: {{ city }}</h1>
  <div id="chart"></div>
  <script>
    // Данные из DataFrame pandas
    var data = {{ temp_data|tojson }};
    var dates = [];
    var temperatures = [];
    for (var i = 0; i < data.length; i++) {
        dates.push(data[i].date);
        temperatures.push(data[i].temperature_2m);
    }
    // Настройка графика
    var trace = {
        x: dates,
        y: temperatures,
        type: 'scatter',
        mode: 'lines+markers',
        name: 'Температура'
    };

    // Создание графика
    var layout = {
        title: 'График Температуры',
        xaxis: {
            title: 'Дата'
        },
        yaxis: {
            title: 'Температура (°C)'
        }
    };

    Plotly.newPlot('chart', [trace], layout);
  </script>
  <table>
    <thead>
      <tr>
        <th>Дата</th>
        <th>Погода</th>
      </tr>
    </thead>
    <tbody>
      {% for row in weather_data.itertuples() %}
      <tr>
        <td>{{ row.date }}</td>
        <td>
          <span
            class="weather-icon"
            style="background-image: url('https://openweathermap.org/img/wn/{{ row.weather_icon }}@2x.png');"
          ></span>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<script>
  const loginButton = document.getElementById("loginButton");
  loginButton.addEventListener("click", () => {
    loginForm.style.display = "block"; // Показать форму входа
  });
</script>
{% endif %} {% endblock %}